# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.hostname = "rails-dev-box"
  config.vm.box = "rails-dev-box"
  config.vm.box_url = "https://s3.amazonaws.com/gsc-vagrant-boxes/ubuntu-12.04-omnibus-chef.box"

  config.vm.network :private_network, :ip => "10.0.1.13"
  config.vm.network :forwarded_port, :guest => 8080, :host => 8080
  config.vm.network :forwarded_port, :guest => 9200, :host => 9200

  config.vm.synced_folder "~", "/home_dir", :nfs => true

  config.vm.provider :virtualbox do |vb|
    vb.customize ["modifyvm", :id, "--memory", "2048"]
  end

  config.ssh.forward_agent = true
  config.ssh.keep_alive = true
end
